name: dreamkg
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_1
- joblib=0.9.4=py35_0
- jpeg=8d=1
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_core=4.2.0=py35_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.3=py35_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- networkx=1.11=py35_0
- nose=1.3.7=py35_1
- notebook=4.2.3=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2i=0
- pandas=0.18.1=np111py35_0
- pango=1.39.0=1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.3.1=py35_0
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py35_0
- psutil=4.3.1=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyzmq=15.4.0=py35_0
- qt=4.8.7=4
- readline=6.2=2
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.17.1=np111py35_2
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.1=py35_0
- traitlets=4.3.0=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - click==6.6
  - gdbn==0.1
  - gnumpy==0.2
  - ipython-genutils==0.1.0
  - ipywidgets
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - prompt-toolkit==1.0.3
  - pydicom==0.9.9
  - pytest==3.0.3
  - tabulate==0.7.5
  - theano==0.8.2
  - "--editable=git+https://github.com/Lasagne/Lasagne.git@61b1ad1#egg=Lasagne==0.2.git"
  - "--editable=git+https://github.com/ottogroup/palladium.git@develop#egg=palladium==1.0.2.a.git"
  - "--editable=git+https://github.com/topiaruss/nolearn.git@68ff839#egg=nolearn==0.7.git"
  - "--editable=git+https://github.com/topiaruss/nolearn_utils.git@e92d757#egg=nolearn_utils==0.1.git"
